server:
  port: 8080

spring:
  ai:
    openai:
      no-think: true
      model: qwen3-8b
#      model: qwq-32b
      base-url: http://localhost:1234
      api-key: NOT_REQUIRED

logging:
  level:
    com.example.openaitextprocessor: DEBUG
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: INFO
